
name: Maven Pull Request Version Validation
description: A composite action to ensure that the version in the PR matches the version in the target.

# Inputs
inputs:
  java_version:
    description: "Java Version"
    required: false
    default: "24"
       
runs:
  using: "composite" 
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
          repository: ikmdev/${{github.event.repository.name}}
          ref: ${{ github.event.repository.default_branch }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{inputs.java_version}}

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Extract Target Version
      id: get_target_version
      shell: bash
      run: |
          echo "TARGET_POM_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT 

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Extract Source Version
      id: get_source_version
      shell: bash
      run: |
          echo "SOURCE_POM_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT 
     
    - name: Validate Version
      if: steps.get_target_version.outputs.TARGET_POM_VERSION != steps.get_source_version.outputs.SOURCE_POM_VERSION
      shell: bash
      run: |
         echo "::error::Source Version & Target Version Does Not Match"
         echo "::error::Source Version: ${{steps.get_source_version.outputs.SOURCE_POM_VERSION}}"
         echo "::error::Target Version: ${{steps.get_target_version.outputs.TARGET_POM_VERSION}}"
         echo "::error::Please sync fork and version"
         exit 1
   
